# Generated by Django 3.2.6 on 2021-09-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_alimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/images')),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='article_electromenager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/images')),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='article_electronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/images')),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='article_vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/images')),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/images')),
                ('desc', models.TextField()),
                ('article_alimentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.article_alimentaire')),
                ('article_electromenager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.article_electromenager')),
                ('article_electronique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.article_electronique')),
                ('article_vetement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.article_vetement')),
            ],
        ),
    ]
