# Generated by Django 3.2.6 on 2021-09-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hebogoundo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_alimentaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_electromenager',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_electronique',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_vetement',
        ),
    ]
