# Generated by Django 3.2.6 on 2021-09-10 23:35

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('hebogoundo', '0002_auto_20210910_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_alimentaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.related.ForeignKey, to='hebogoundo.article_alimentaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_electromenager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.related.ForeignKey, to='hebogoundo.article_electromenager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_electronique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.related.ForeignKey, to='hebogoundo.article_electronique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_vetement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.related.ForeignKey, to='hebogoundo.article_vetement'),
            preserve_default=False,
        ),
    ]
