# Generated by Django 3.2.6 on 2021-09-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hebogoundo', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_alimentaire',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_electromenager',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_electronique',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_vetement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hebogoundo.category'),
            preserve_default=False,
        ),
    ]
