# Generated by Django 3.2.6 on 2021-09-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hebogoundo', '0005_auto_20210912_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_alimentaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_electromenager',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_electronique',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_vetement',
        ),
    ]
